In [3]:
# Importar Pandas e Matplotlib
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Importação dos dados
df = pd.read_csv('data/raw.csv')

In [5]:
# Exibir os tipos de dados de cada coluna para verificar a necessidade de atuação
df.dtypes

Idade                       int64
Genero                     object
Nivel Ensino               object
Area Formacao              object
Setor                      object
Nivel                      object
Faixa Salarial             object
Anos experiencia           object
Faixa Salarial – numero     int64
Data ultimo aumento        object
dtype: object

In [6]:
# Transformando a coluna 'Data ultimo aumento' para datetime
df['Data ultimo aumento'] = pd.to_datetime(df['Data ultimo aumento'])

C:\Users\Enrique\AppData\Local\Temp\ipykernel_9660\4139712609.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Data ultimo aumento'] = pd.to_datetime(df['Data ultimo aumento'])

In [7]:
# Separando colunas numéricas e categóricas
numerical_cols = [col for col in df.columns if df[col].dtype != 'object' and df[col].dtype != 'datetime64[ns]']
categorical_cols = [col for col in df.columns if df[col].dtype == 'object']

In [8]:
# Resumo das colunas numéricas
df[numerical_cols].describe()

             Idade  Faixa Salarial – numero
count  1385.000000              1385.000000
mean     30.779783              9992.779783
std       6.869018              7353.675097
min      18.000000              1000.000000
25%      26.000000              6000.000000
50%      29.000000              8000.000000
75%      34.000000             12000.000000
max      54.000000             45000.000000

In [9]:
# Resumo das colunas categóricas
df[categorical_cols].describe()

,Genero,Nivel Ensino,Area Formacao,Setor,Nivel,Faixa Salarial,Anos experiencia
count,1385,1385,1361,1385,1385,1385,1385
unique,2,6,9,23,4,13,6
top,Masculino,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Tecnologia/Fábrica de Software,Pleno,de R$ 8.001/mês a R$ 12.000/mês,de 2 a 3 anos
freq,979,495,588,372,440,295,314

In [10]:
# Verificar se existem valores faltantes nas colunas
df.isna().any()

Idade                      False
Genero                     False
Nivel Ensino               False
Area Formacao               True
Setor                      False
Nivel                      False
Faixa Salarial             False
Anos experiencia           False
Faixa Salarial – numero    False
Data ultimo aumento        False
dtype: bool

In [11]:
# Verificar a quantidade de valores faltantes em cada coluna
df.isna().sum()

Idade                       0
Genero                      0
Nivel Ensino                0
Area Formacao              24
Setor                       0
Nivel                       0
Faixa Salarial              0
Anos experiencia            0
Faixa Salarial – numero     0
Data ultimo aumento         0
dtype: int64

In [27]:
# Tratar os valores faltantes em Area Formação por: "Não informado":
df['Area Formacao'].fillna('Não informado', inplace=True)

In [ ]:
# Verificar se existem valores duplicados
df.duplicated().sum()

np.int64(0)

In [14]:
# Contagem de valores por categoria de 'Nivel'
df['Nivel'].value_counts()

Nivel
Pleno     440
Júnior    409
Sênior    370
Gestor    166
Name: count, dtype: int64

In [15]:
# Contagem de valores por categoria de 'Faixa Salarial'
df['Faixa Salarial'].value_counts()

Faixa Salarial
de R$ 8.001/mês a R$ 12.000/mês     295
de R$ 6.001/mês a R$ 8.000/mês      255
de R$ 4.001/mês a R$ 6.000/mês      242
de R$ 12.001/mês a R$ 16.000/mês    140
de R$ 3.001/mês a R$ 4.000/mês      113
de R$ 2.001/mês a R$ 3000/mês       108
de R$ 1.001/mês a R$ 2.000/mês       79
de R$ 16.001/mês a R$ 20.000/mês     59
de R$ 20.001/mês a R$ 25.000/mês     26
de R$ 25.001/mês a R$ 30.000/mês     22
Menos de R$ 1.000/mês                19
de R$ 30.001/mês a R$ 40.000/mês     18
Acima de R$ 40.001/mês                9
Name: count, dtype: int64